### ISSUE TITLE
Feature: Allow user to invite bot

### ISSUE THREAD

**Issue by CubicrootXYZ** [CubicrootXYZ/matrix-reminder-and-calendar-bot#28]
**Is your feature request related to a problem? Please describe.**
Currently all users that can interact with the bot need to be hardcoded on the config file. This is good from a privacy standpoint but bad from a user experience standpoint. So add an option that allows users to invite the bot into a channel.

**Describe the solution you'd like**
1. User invites bot
2. Bot joins channel
3. User can interact with the bot

**Describe alternatives you've considered**
Manually setting users in the config file is no practical solution to provide the bot to a bigger audience.

Only allow known users to add others is also not very practical for wider audiences.

**Additional context**
From this [discussion](https://github.com/CubicrootXYZ/matrix-reminder-and-calendar-bot/discussions/26)

**Comment by kojid0** [comment]
Don't know if this helps but MINA Matrix bot handles it this way (bot is in German). You might want to check out its [code on github](https://github.com/djmaze/nina-matrix-bot).

**Comment by CubicrootXYZ** [comment]
A few tasks I extracted for now:
- [ ] Allow bot to recognize invitations and add channels for those
- [ ] Add permissions to the application (admin/usual user) for commands and the api
- [ ] Change channel sync "algorithm" (delete only admin accounts removed from the config file but no regulare users that invited the bot themselves)
- [ ] Improve performance (database indexes)

**Comment by CubicrootXYZ** [comment]
Inviting the bot into encrypted channels behaves really weird - I am getting 4 invites with different room IDs. Need to investigate that further.

**Comment by CubicrootXYZ** [comment]
> 
> 
> Inviting the bot into encrypted channels behaves really weird - I am getting 4 invites with different room IDs. Need to investigate that further.

Seems to have fixed itself? Maybe those were just old invites hanging around. But I found another odd behaviour: when kicking and then re-inviting the bot he receives the leave event twice. Maybe this is also related to old events hanging around. Might need to introduce a storage for the events already handled.

**Comment by CubicrootXYZ** [comment]
> Maybe this is also related to old events hanging around. Might need to introduce a storage for the events already handled.

Introducing a storage indeed helped. It is now part of the branch. The branch can be used for testing as all basic features are implemented. 

Permissions are currently not used as there aren't any critical calls a user can make. For the invitations I still need to find a way to restrict invites somehow. Black- or Whitelisting might be an option but also not that easy to use. Maybe a dumb user limit might be sufficient? This will also help in reducing the risk of running into matrix API rate limits.

**Comment by CubicrootXYZ** [comment]
> Maybe a dumb user limit might be sufficient?

Added one to the branch. I think this feature is then nearly complete. However it is not tested well yet.
